name: continous deployment

on: push

env:
  AWS_REGION: us-east-1
  CDN_DEFAULT_TTL: 3600
  CDN_MAX_TTL: 7200
  CDN_MIN_TTL: 1800
  CDN_ROOT_OBJECT: index.html
  FUNC_MEMORY_SIZE: 120
  FUNC_TIMEOUT: 3
  FUNC_LOG_RETENTION_DAYS: 7

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.1

      - name: map branch 2 test/prod
        run: |
          if [[ ${{ github.ref }} == *master ]]; then
            echo ::set-env name=_ENVIRONMENT::prod
          else
            echo ::set-env name=_ENVIRONMENT::test
          fi

      - name: configure the environment
        id: configure_environment
        run: |
          echo "::set-env name=_STACK_NAME::payola-$_ENVIRONMENT"
          echo "::set-env name=_BUCKET_NAME::payola-$_ENVIRONMENT-bucket"
          echo "::set-env name=_GET_BALANCE_HANDLER_NAME::payola-$_ENVIRONMENT-getbalanceHandler"
          echo "::set-output name=_stack_name::payola-$_ENVIRONMENT"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: deploy payola stack
        run: |
          aws cloudformation deploy \
            --template-file=./compute/stack.yml \
            --stack-name=${{ env._STACK_NAME }} \
            --parameter-overrides \
              BucketName=${{ env._BUCKET_NAME }} \
              Environment=${{ env._ENVIRONMENT }} \
              DefaultRootObject=${{ env.CDN_ROOT_OBJECT }} \
              DefaultTTL=${{ env.CDN_DEFAULT_TTL }} \
              MaxTTL=${{ env.CDN_MAX_TTL }} \
              MinTTL=${{ env.CDN_MIN_TTL }} \
              FunctionLogRetentionInDays=${{ env.FUNC_LOG_RETENTION_DAYS }} \
              FunctionMemorySize=${{ env.FUNC_MEMORY_SIZE }} \
              FunctionTimeout=${{ env.FUNC_TIMEOUT }} \
              GetBalanceHandlerName=${{ env._GET_BALANCE_HANDLER_NAME }} \
            --capabilities=CAPABILITY_IAM \
            --no-fail-on-empty-changeset
