name: continous deployment
on:
  push:
    branches:
      - master
      - open-api-spec
    paths:
      - ./stacks/api/open-api.yaml
      - cd.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v1.0.0
      - name: authenticate with aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: validate the open api spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate ./stacks/api/open-api.yaml"
      # - name: generate the api docs in pdf format
      #   run: |
      #     swagger2pdf -y -s ./stacks/api/open-api.yaml -o ./stacks/api/
      # - name: validate the cloudformation template
      #   run: |
      #     aws cloudformation validate-template \
      #       --template-body="$(cat ./stack.yml)"
      # - name: deploy the web stack
      #   run: |
      #     aws cloudformation deploy \
      #       --stack-name=${{ secrets.AWS_CLOUDFORMATION_STACK_NAME }} \
      #       --template-body="$(cat ./stack.yml)" \
      #       --capabilities=CAPABILITY_IAM
#      - name: update the website content
#        run: aws s3 cp ./index.html s3://${{ secrets.AWS_S3_BUCKET_NAME_MASTER }}
